Repository HIM-Health-Indoor-Machine/him-frontend, pull requests merged in 2024-11, with the labels that each got.

#9 화면 구현 : 로그인/회원가입, 마이페이지
  src/views/LoginView.vue
  src/views/MyPageView.vue
  src/views/SignUpView.vue
Labels: feat

#13 화면 구현 : 로딩, 성공, 실패
  src/components/FailScreen.vue
  src/components/LoadingScreen.vue
  src/components/SuccessScreen.vue
Labels: feat

#15 화면 구현 : 홈
  package-lock.json
  package.json
  src/App.vue
  src/assets/images/character/example.jpg
  src/assets/images/icon/info-icon.png
  src/assets/images/icon/setting-icon.png
  src/assets/images/tier/tier_BRONZE.png
  src/assets/images/tier/tier_DIAMOND.png
  src/assets/images/tier/tier_EMERALD.png
  src/assets/images/tier/tier_GOAT.png
  src/assets/images/tier/tier_GOLD.png
  src/assets/images/tier/tier_IRON.png
  src/assets/images/tier/tier_LEGEND.png
  src/assets/images/tier/tier_MASTER.png
  src/assets/images/tier/tier_PLATINUM.png
  src/assets/images/tier/tier_SILVER.png
  src/components/ModeSelect.vue
  src/components/SuccessScreen.vue
  src/router/index.js
  src/views/ChallengeSelectView.vue
  src/views/GamePlayView.vue
  src/views/GameSelectView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/MyPageView.vue
  src/views/SignUpView.vue
Labels: documentation, feat

#21 화면 구현 : 챌린지 플레이, 게임 플레이
  src/router/index.js
  src/utils/teachableMachineForChallenge.js
  src/utils/teachableMachineForGame.js
  src/views/ChallengePlayView.vue
  src/views/GamePlayView.vue
Labels: feat

#22 시작 화면 구현 및 스타일 변경
  index.html
  src/assets/images/logo/logo.png
  src/assets/main.css
  src/components/FailScreen.vue
  src/components/LoadingScreen.vue
  src/components/SuccessScreen.vue
  src/router/index.js
  src/views/ChallengePlayView.vue
  src/views/ChallengeSelectView.vue
  src/views/GamePlayView.vue
  src/views/GameSelectView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/SignUpView.vue
  src/views/StartView.vue
Labels: feat

#25 네비게이션 바 생성 및 적용
  src/App.vue
  src/components/HeaderNav.vue
  src/views/GameSelectView.vue
Labels: feat

#24 페이지 이동 구현
  src/views/ChallengeSelectView.vue
  src/views/GamePlayView.vue
  src/views/GameSelectView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
Labels: feat

#37 버튼 기능과 페이지 이동
  src/App.vue
  src/components/FailScreen.vue
  src/components/SuccessScreen.vue
  src/views/ChallengeSelectView.vue
Labels: feat

#38 네비게이션 바 디자인 수정
  src/assets/images/icon/heart-icon.png
  src/components/HeaderNav.vue
  src/components/LoadingScreen.vue
  src/views/GameSelectView.vue
  src/views/SignUpView.vue
Labels: fix

#39 플레이 화면 구성
  src/utils/teachableMachineForChallenge.js
  src/utils/teachableMachineForGame.js
  src/views/ChallengePlayView.vue
  src/views/GamePlayView.vue
  src/views/HomeView.vue
  src/views/StartView.vue
Labels: feat

#34 router 수정
  src/components/HeaderNav.vue
  src/router/index.js
Labels: fix

#29 홈 화면 - 프로필 캐릭터 선택 기능 추가 및 경험치 설명 아이콘 추가
  src/assets/images/character/character_BEAR.png
  src/assets/images/character/character_CAT.png
  src/assets/images/character/character_CHICK.png
  src/assets/images/character/character_DOG.png
  src/assets/images/character/character_KOALA.png
  src/assets/images/character/character_MONKEY.png
  src/assets/images/character/character_PANDA.png
  src/assets/images/character/character_TIGER.png
  src/assets/images/character/example.jpg
  src/assets/images/icon/info-icon.png
  src/components/HeaderNav.vue
  src/views/HomeView.vue
Labels: feat

#42 게임 - API 연결
  package-lock.json
  package.json
  src/components/FailScreen.vue
  src/components/SuccessScreen.vue
  src/main.js
  src/stores/game.js
  src/views/GamePlayView.vue
  src/views/GameSelectView.vue
Labels: feat

#44 ChallengeSelectView 연동
  src/stores/challenge.js
  src/stores/counter.js
  src/views/ChallengeSelectView.vue
Labels: feat

#45 challengePlayView API 연동 작업
  src/router/index.js
  src/stores/ todayChallenge.js
  src/views/ChallengePlayView.vue
  src/views/ChallengeSelectView.vue
Labels: feat

#50 HomeView, HeaderNav 연동
  src/assets/imageAssets.js
  src/components/HeaderNav.vue
  src/composables/useAchievedExp.js
  src/router/index.js
  src/stores/ todayChallenge.js
  src/stores/attendance.js
  src/stores/challenge.js
  src/stores/game.js
  src/stores/todayChallenge.js
  src/stores/user.js
  src/utils/tierData.js
  src/utils/tierUtils.js
  src/views/ChallengePlayView.vue
  src/views/ChallengeSelectView.vue
  src/views/GameSelectView.vue
  src/views/HomeView.vue
Labels: feat

#51 GameSelectView와 ChallengeSelectView에 info container 구현 및 api 연동
  src/composables/useAchievedExp.js
  src/composables/useProcessedChallenges.js
  src/views/ChallengeSelectView.vue
  src/views/GameSelectView.vue
  src/views/HomeView.vue
Labels: feat

#54 챌린지 지연 시간 해결
  package-lock.json
  package.json
  src/views/ChallengePlayView.vue
  src/views/GamePlayViewBomb.vue
  src/views/GamePlayViewDuck.vue
  src/views/GamePlayViewFlying.vue
Labels: feat

#58 GithubAction을 이용한 CICD 파이프라인 구축 및 S3를 이용한 정적 웹사이트 호스팅
  .github/workflows/deploy.yml
Labels: infra

#59 회원가입/로그인/로그아웃 기능 구현
  src/components/HeaderNav.vue
  src/components/Modal.vue
  src/plugins/setupAxios.js
  src/router/index.js
  src/stores/attendance.js
  src/stores/auth.js
  src/stores/challenge.js
  src/stores/game.js
  src/stores/todayChallenge.js
  src/stores/user.js
  src/views/GamePlayViewBomb.vue
  src/views/GamePlayViewDuck.vue
  src/views/GamePlayViewFlying.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/SignUpView.vue
Labels: feat

#62 챌린지 박스 버그 해결
  src/stores/challenge.js
  src/views/ChallengeSelectView.vue
Labels: fix

#63 챌린지 목록 예외 처리
  src/views/ChallengeSelectView.vue
  src/views/HomeView.vue
Labels: feat

#65 챌린지 조회 시, userId 값 수정
  src/views/ChallengeSelectView.vue
Labels: fix

#66 accesstoken 갱신 후 로그아웃 실패 에러 해결
  src/components/HeaderNav.vue
  src/stores/auth.js
  src/views/HomeView.vue
Labels: bug

#69 플레이 뷰 개선
  src/components/FailScreen.vue
  src/router/index.js
  src/stores/game.js
  src/views/ChallengePlayView.vue
  src/views/GamePlayView.vue
  src/views/GamePlayViewBomb.vue
  src/views/GamePlayViewFlying.vue
  src/views/GameSelectView.vue
Labels: enhancement, feat

#73 챌린지 카운트 버그 해결 및 게임 난이도 재조정
  src/components/FailScreen.vue
  src/components/SuccessScreen.vue
  src/plugins/setupAxios.js
  src/router/index.js
  src/utils/teachableMachine.js
  src/views/ChallengePlayView.vue
  src/views/GamePlayView.vue
  src/views/GameSelectView.vue
Labels: bug, enhancement, fix

#74 챌린지 로직 관련 에러 해결
  src/components/ChallengeSuccessScreen.vue
  src/stores/challenge.js
  src/views/ChallengePlayView.vue
  src/views/ChallengeSelectView.vue
Labels: bug

#76 자세 연습 모드 적용
  index.html
  public/images/logo/logo.png
  src/assets/images/postures/pushup-posture.png
  src/assets/images/postures/squat-posture.png
  src/components/HeaderNav.vue
  src/router/index.js
  src/utils/teachableMachine.js
  src/views/ChallengePlayView.vue
  src/views/GamePlayView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/SignUpView.vue
  src/views/StartView.vue
  src/views/WebcamView.vue
Labels: feat

#77 challenge 진행 정보의 성취 갯수 정보 수정
  src/views/ChallengePlayView.vue
Labels: fix

#78 튜토리얼 추가
  src/views/GamePlayView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
Labels: feat

#81 챌린지 생성 관련 에러 해결
  src/composables/useProcessedChallenges.js
  src/stores/challenge.js
  src/views/ChallengeSelectView.vue
Labels: bug

#84 fix : challenge info 상태 조건 수정
  src/views/ChallengeSelectView.vue
  src/views/HomeView.vue
Labels: fix

#85 백엔드 ip 주소 변경 및 소스 코드 변경
  src/plugins/setupAxios.js
  src/stores/auth.js
  src/views/ChallengeSelectView.vue
  src/views/HomeView.vue
Labels: fix

#86 성공 화면 티어 사진 CSS 변경
  src/components/ChallengeSuccessScreen.vue
  src/components/SuccessScreen.vue
Labels: fix

#87 티어 사진 스타일 변경
  src/components/ChallengeSuccessScreen.vue
  src/components/SuccessScreen.vue
Labels: fix

#88 프로젝트 설명 추가
  README.md
Labels: documentation
